### ISSUE TITLE
Package/Repo consistent name

### ISSUE THREAD

**Issue by eriktks** [sequgen/sequgen#11]
---

Migrated from https://github.com/epodium/time_series_generator/issues/39
Originally created by @sverhoeven on *Tue, 23 Mar 2021 11:15:06 GMT*

---
Now repo is called `time_series_generator` while to import the package you need to use `from ts_generator import TS_generator`.
It would be nice if names would be consistent.

Also ties in with moving efforts at #25

**Comment by sverhoeven** [comment]
Its now called `sequgen` everywhere
