### ISSUE TITLE
Ask reddit, twitter how they would solve the problem of generating complex noise time series

### ISSUE THREAD

**Issue by eriktks** [sequgen/sequgen#19]
---

Migrated from https://github.com/epodium/time_series_generator/issues/23
Originally created by @jspaaks on *Mon, 15 Mar 2021 11:02:06 GMT*

---

**Comment by eriktks** [comment]
---

Migrated from https://github.com/epodium/time_series_generator/issues/23#issuecomment-800280196
Originally created by @eriktks on *Tue, 16 Mar 2021 13:58:28 GMT*

---
Reddit question: https://www.reddit.com/r/DSP/comments/m5jrjf/how_to_generate_complex_noise_time_series/

**Comment by eriktks** [comment]
To do: summarize results of query on reddit

**Comment by fdiblen** [comment]
responded to the comments.
