### ISSUE TITLE
move test models to notebooks repository

### ISSUE THREAD

**Issue by eriktks** [sequgen/sequgen#36]
involves both moving the files and converting them to notebooks

**Comment by jspaaks** [comment]
PR https://github.com/sequgen/notebooks/pull/1

**Comment by sverhoeven** [comment]
We still need to link from the sequgen README/docs to the notebooks at https://github.com/sequgen/notebooks, as someone visiting via PyPi or RSD will likely not look at other repos in GH org. 

Is the linking a new issue? Or part of this one?

**Comment by eriktks** [comment]
Good suggestion. I have created a new issue for linking the `docs` section to `notebooks`: #52

**Comment by eriktks** [comment]
The two test files have been converted to notebooks (PR [sequegen/notebooks#1](https://github.com/sequgen/notebooks/pull/1)). There is no need to put the original scripts there anymore since we will have only notebooks there. Further work on the notebooks can be done as part of two other issues: #50 and #51. A remaining issue regarding linking the notebooks has also been split off in a separate issue (#52). As far as I am concerned this issue can be closed.
