### ISSUE TITLE
Default values expect t_predict with timestep <1

### ISSUE THREAD

**Issue by sverhoeven** [sequgen/sequgen#61]
Some default arguments depend what t_predict is. This causes negative values and weirdness.

* normal_peak, location ~and stddev~ args
* sine, ~phase_shift and~ wavelength args
* triangular_peak, all width* args

I would suggest to remove the default values and always let the user supply them.

**Comment by jspaaks** [comment]
> Some default arguments depend what t_predict is.

I don't think this is accurate

**Comment by jspaaks** [comment]
- normal peak: I suggest we keep `stddev=1.0` (that is what makes standard normal standard normal)
- sine: `wavelength` now required, `phase_shift` still uses default . I suggest we keep it that way
- triangular peak, open for discussion

**Comment by sverhoeven** [comment]
You are right, 
* stddev deals with height not time position, I agree lets keep the default
* phase_shift deals with height not time position,  I agree lets keep the default

The changes in #80 and the docstring makes my [confusion](https://github.com/sequgen/sequgen/blob/35915947c3665ff1038544075f1ccf5ca97c84d7/tests/deterministic/test_triangular_peak.py#L12-L32) go away.

**Comment by jspaaks** [comment]
> The changes in #80 and the docstring makes my confusion go away.

I guess that's the main thing!

BTW `phase_shift` does affect the position along the horizontal axis but OK.

**Comment by jspaaks** [comment]
With recent additions, we can close this
